### ISSUE TITLE
Grammar error in line 136 in app.js

### ISSUE THREAD

**Issue by bliekp** [athombv/com.wolframalpha#1]
app.speakOutput ("Sorry, Homey coudn't found what you are looking for!");

Should be:

                app.speakOutput ("Sorry, Homey couldn't find what you are looking for!");

**Comment by freekwebdesign** [comment]
Thanks for noticing
Fixed in version 1.2.3

**Comment by matjaz** [comment]
can be closed. see 0c4dbd70498460e61c0e83560a9364c97449bebd
